name: flunt_dart
description: Library that provides a fluent way to use Notification Pattern.
version: 0.4.0
homepage: https://github.com/PedroBissonho/flunt-dart
author: Pedro Bissonho <pedro.bissonho@gmail.com>

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  
dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.3